ATT1:
  prep_time: 3
  exec_time: 10
  objects: 6
  decoys: 3
  tables: 5
  shelfes_placing: 1
  pp_placing: 1
  arbitrary_surfaces: 2
  obstacles: 0
  barrier_tapes: 2
  normal_table_types: [ "00","05","10","15" ]
