BTT1:
  prep_time: 5
  exec_time: 6
  objects: 5
  decoys: 0
  tables: 3
  ref_position: true
  ref_rotation: true
  arbitrary_surfaces: 0
  obstacles: 0
  barrier_tape: 0
  normal_table_types: [ "10" ]
