# Object.msg

uint16 object
uint16 target
bool   decoy
geometry_msgs/PoseStamped pose

uint16 EMPTY = 0

# atwork
uint16 ATWORK_START = 11
uint16 F20_20_B     = 11
uint16 F20_20_G     = 12
uint16 S40_40_B     = 13
uint16 S40_40_G     = 14
uint16 M20_100      = 15
uint16 M20          = 16
uint16 M30          = 17
uint16 R20          = 18
uint16 ATWORK_END   = 18

# advanced
uint16 ADVANCED_START = 20
uint16 Axis2          = 20
uint16 Bearing2       = 21
uint16 Housing        = 22
uint16 Motor2         = 23
uint16 Spacer         = 24
uint16 Screwdriver    = 25
uint16 Wrench         = 26
uint16 Drill          = 27
uint16 AllenKey       = 28
uint16 ADVANCED_END   = 28

# rockin
uint16 ROCKIN_START  = 30
uint16 BEARING_BOX   = 31
uint16 BEARING       = 32
uint16 AXIS          = 33
uint16 DISTANCE_TUBE = 34
uint16 MOTOR         = 35
uint16 ROCKIN_END    = 35

# container
uint16 CONTAINER_START = 40
uint16 CONTAINER_RED   = 40
uint16 CONTAINER_BLUE  = 41
uint16 CONTAINER_END   = 41

# cavity
uint16 CAVITY_START = 50
uint16 F20_20_H     = 50
uint16 F20_20_V     = 51
uint16 F20_20_F     = 52
uint16 S40_40_H     = 53
uint16 S40_40_V     = 54
uint16 S40_40_F     = 55
uint16 M20_H        = 56
uint16 M20_V        = 57
uint16 M20_F        = 58
uint16 M20_100_H    = 59
uint16 M20_100_V    = 60
uint16 M20_100_F    = 61
uint16 M30_H        = 62
uint16 M30_V        = 63
uint16 M30_F        = 64
uint16 R20_H        = 65
uint16 R20_V        = 66
uint16 R20_F        = 67
uint16 CAVITY_END   = 67
